GAME_DATA = {
    "en": {
        "ui": {
            "title": "Battleship",
            "enter_name": "Enter your name",
            "room": "Room",
            "create_room": "Create room",
            "join_room": "Join room",
            "room_id": "Room ID",
            "language": "Language",
            "waiting_opponent": "Waiting for opponent…",
            "lobby_ready_hint": "When both players are ready, the game starts.",
            "place_ships": "Place your ships",
            "orientation": "Orientation",
            "horizontal": "Horizontal",
            "vertical": "Vertical",
            "clear": "Clear",
            "ready": "Ready",
            "not_ready": "Not ready",
            "your_turn": "Your turn",
            "opponent_turn": "Opponent's turn",
            "fire": "Fire",
            "hit": "Hit!",
            "miss": "Miss",
            "sunk": "Sunk!",
            "invalid_placement": "Invalid placement",
            "invalid_move": "Invalid move",
            "game_over": "Game over",
            "you_win": "You win!",
            "you_lose": "You lose.",
            "opponent_left": "Opponent disconnected.",
            "copy_link": "Copy link",
            "copied": "Copied!",
        },
        "ships": {
            "fleet": [4, 3, 3, 2, 2, 2, 1, 1, 1, 1],
            "fleet_label": "Fleet",
        },
    },
    "ru": {
        "ui": {
            "title": "Морской бой",
            "enter_name": "Введите имя",
            "room": "Комната",
            "create_room": "Создать комнату",
            "join_room": "Войти в комнату",
            "room_id": "Код комнаты",
            "language": "Язык",
            "waiting_opponent": "Ждём соперника…",
            "lobby_ready_hint": "Когда оба игрока готовы — игра начнётся.",
            "place_ships": "Расставьте корабли",
            "orientation": "Ориентация",
            "horizontal": "Горизонтально",
            "vertical": "Вертикально",
            "clear": "Очистить",
            "ready": "Готов",
            "not_ready": "Не готов",
            "your_turn": "Ваш ход",
            "opponent_turn": "Ход соперника",
            "fire": "Стрелять",
            "hit": "Попадание!",
            "miss": "Мимо",
            "sunk": "Потоплен!",
            "invalid_placement": "Неверная расстановка",
            "invalid_move": "Недопустимый ход",
            "game_over": "Игра окончена",
            "you_win": "Вы победили!",
            "you_lose": "Вы проиграли.",
            "opponent_left": "Соперник отключился.",
            "copy_link": "Скопировать ссылку",
            "copied": "Скопировано!",
        },
        "ships": {
            "fleet": [4, 3, 3, 2, 2, 2, 1, 1, 1, 1],
            "fleet_label": "Флот",
        },
    },
    "bg": {
        "ui": {
            "title": "Морски бой",
            "enter_name": "Въведи име",
            "room": "Стая",
            "create_room": "Създай стая",
            "join_room": "Влез в стая",
            "room_id": "Код на стая",
            "language": "Език",
            "waiting_opponent": "Изчакване на противник…",
            "lobby_ready_hint": "Когато и двамата са готови — играта започва.",
            "place_ships": "Постави корабите си",
            "orientation": "Ориентация",
            "horizontal": "Хоризонтално",
            "vertical": "Вертикално",
            "clear": "Изчисти",
            "ready": "Готово",
            "not_ready": "Не е готово",
            "your_turn": "Твой ход",
            "opponent_turn": "Ход на противника",
            "fire": "Стреляй",
            "hit": "Попадение!",
            "miss": "Пропуск",
            "sunk": "Потопен!",
            "invalid_placement": "Невалидно поставяне",
            "invalid_move": "Невалиден ход",
            "game_over": "Край на играта",
            "you_win": "Ти печелиш!",
            "you_lose": "Ти губиш.",
            "opponent_left": "Противникът се изключи.",
            "copy_link": "Копирай линк",
            "copied": "Копирано!",
        },
        "ships": {
            "fleet": [4, 3, 3, 2, 2, 2, 1, 1, 1, 1],
            "fleet_label": "Флот",
        },
    },
}
